# Generated by Django 5.1.7 on 2025-03-25 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=10, verbose_name='积分')),
                ('last_login_reward_date', models.DateField(blank=True, null=True, verbose_name='上次登录奖励日期')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='VideoParsingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(verbose_name='视频URL')),
                ('parsed_result', models.JSONField(verbose_name='解析结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsing_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '视频解析记录',
                'verbose_name_plural': '视频解析记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
